import Markdown from '@/components/markdown';

const VERIFIABLE_AUTONOMY = `
# Verifiable Autonomy

You are sending your commitments to an ethereum address which is not a smart contract but a wallet controlled by @getduinbot.
How do you verify that only @getduinbot no other human or agent has control over this address?

All the code of the agent is available on [github](https://github.com/AlwaysHungrie/duin.fun), 
but how do verify any response generated by the agent was generated by running this exact code?

### Verifiable Autonomy is the next major feature to be shipped by the duin team. If verifiable autonomy interests you as much as us, send us a [cheer](/docs/cheer) on this [post](https://x.com/getduinbot/status/1841188188888888888).
`

export default function VerifiableAutonomy() {
  return <Markdown content={VERIFIABLE_AUTONOMY} />
}


